Fix AttributeError: 'Namespace' object has no attribute 'cpu_pwr_svi_telemetry_rails'
Updated missing references to cpu_pwr_svi_telemetry_rails

Change-Id: I1828ad3122a602dc5c4253500f83c3910b682cb3
Signed-off-by: Poag, Charis <Charis.Poag@amd.com>